### ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

In [57]:
import numpy as np
from collections import Counter

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [6]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [8]:
arr = np.arange(3)
print(arr.shape)

arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


In [9]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [10]:
print(arr[2])
print(arr[2:4])
print(arr[::-1])


1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [11]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [13]:
nd_array[1][2]
nd_array[1, 2] #!

3.0

In [14]:
nd_array[:2, 2]

array([1., 3.])

In [15]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [16]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [28]:
nd_array[:2]


array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [30]:
mystery = np.array([
    [-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
    [25936, -30968,  -1297,  -4593,   6451, 15790,   7181],
    [13348,  28049,  28655,  -6012,  21762,  25397,   8225],
    [13240,   7994,  32592,  20149,  13754,  11795,   -564],
    [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
    [-16841, -25392, -17278,  11740,   5916,    -47, -32037]
 ])
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4,2]

# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[5,6]

# В переменную line_4 сохраните строку 4
line_4 = mystery[3, :]

# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, 5]

# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = mystery[1:4, 2:5]

#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, 6]

# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()
print(mystery)
print(col_2)
print(rev)


[[-13586  15203  28445 -27117  -1781 -17182 -18049]
 [ 25936 -30968  -1297  -4593   6451  15790   7181]
 [ 13348  28049  28655  -6012  21762  25397   8225]
 [ 13240   7994  32592  20149  13754  11795   -564]
 [-21725  -8681  30305  22260 -17918  12578  29943]
 [-16841 -25392 -17278  11740   5916    -47 -32037]]
[-17182  15790  25397  11795  12578    -47]
[-32037  29943   -564   8225   7181 -18049]


#### Способ 1
* Функция np.sort(<массив>) возвращает новый отсортированный массив:

In [31]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


#### Способ 2
* Функция <массив>.sort() сортирует исходный массив и возвращает None:

In [32]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
print(arr)

None
[ 3  4 12 12 15 23 23 45]


Пропущенные данные

In [46]:
data = np.array([4, 9, -4, 3])

In [47]:
roots = np.sqrt(data)
roots

C:\Users\Raptor\AppData\Local\Temp\ipykernel_17468\3752651322.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

NumPy выдал предупреждение о том, что в функцию sqrt попало некорректное значение. Это было число -4, а как вы помните, корень из отрицательного числа в действительных числах не берётся. Однако программа не сломалась окончательно, а продолжила работу. На том месте, где должен был оказаться корень из -4, теперь присутствует объект nan. Он расшифровывается как Not a number (не число). Этот объект аналогичен встроенному типу None, но имеет несколько отличий:

In [48]:
print(type(None))
print(type(np.nan))
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

In [36]:
print(None == None)
print(np.nan == np.nan)


True
False


In [37]:
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

True
True
False


In [49]:
sum(roots)

nan

In [50]:
np.isnan(roots)

array([False, False,  True, False])

In [51]:
nans_index = np.isnan(roots)

In [58]:
counter = Counter(nans_index)
counter[True]

1

In [54]:
unique, counts = np.unique(nans_index, return_counts=True)

In [56]:
counts

array([3, 1], dtype=int64)

In [40]:
roots[np.isnan(roots)]

array([nan])

In [41]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [42]:
sum(roots)

6.732050807568877