In [3]:
import numpy as np
np.random.rand()

0.6465077795650006

In [8]:
np.random.rand() * 100

48.35720105840531

In [9]:
np.random.rand(5)

array([0.04592028, 0.7988063 , 0.29397845, 0.80303856, 0.11632293])

In [10]:
np.random.rand(2, 3)

array([[0.95387829, 0.97962712, 0.91025956],
       [0.78112557, 0.10387629, 0.54990437]])

In [38]:
# Функция rand может принимать неограниченное число целых чисел для задания формы массива:
np.random.rand(2, 3, 4, 10, 12, 23)

In [12]:
# Если передать в rand кортеж, возникнет ошибка
shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [13]:
# Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:
shape = (3, 4)
np.random.rand(*shape)

array([[0.30604485, 0.72192217, 0.88224761, 0.4808349 ],
       [0.14341157, 0.74605659, 0.0631131 , 0.82500832],
       [0.27389554, 0.43207754, 0.906694  , 0.03356113]])

In [14]:
# Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1,
# которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:
shape = (2, 3)
np.random.sample(shape)

array([[0.15815009, 0.56248599, 0.62704766],
       [0.97430082, 0.92670053, 0.80246857]])

In [15]:
# Не всегда требуются числа в диапазоне именно от 0 до 1.
# На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон,
# однако это не требуется делать самостоятельно — в NumPy доступна функция uniform:

# uniform(low=0.0, high=1.0, size=None)

# Первые два аргумента — нижняя и верхняя границы диапазона в формате float, 
# третий опциональный аргумент — форма массива (если не задан, возвращается одно число). 
# Форма массива задаётся кортежем или одним числом.

np.random.uniform()


0.006235846117964683

In [16]:
np.random.uniform(-30, 50)

-6.643615373217322

In [17]:
np.random.uniform(0.5, 0.75, size=5)

array([0.53420108, 0.64459307, 0.6949962 , 0.52868043, 0.50209794])

In [18]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[  85.86180625, -369.22071241, -638.27183008],
       [  23.00507377,  -91.88531907, -889.52230716]])

### ГЕНЕРАЦИЯ INT

- randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

* Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
* Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
* size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
* dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.


In [19]:
# Сгенерируем таблицу 2x3 от 0 до 3 включительно:
np.random.randint(4, size=(2,3))

array([[3, 1, 3],
       [3, 1, 2]])

In [20]:
np.random.randint(6, 12, size=(3,3))

array([[ 6, 11,  9],
       [11,  8,  7],
       [ 7,  6,  8]])

#### ГЕНЕРАЦИЯ ВЫБОРОК

In [21]:
# Возьмём массив из целых чисел от 0 до 5 и перемешаем его:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))
arr

[0 1 2 3 4 5]
None


array([2, 1, 5, 4, 3, 0])

In [22]:
# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation.
# Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['Pink Floyd' 'Deep Purple' 'ACDC' 'The Beatles']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [23]:
# Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n),
# где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.
np.random.permutation(10)

array([0, 6, 9, 5, 1, 3, 4, 2, 7, 8])

Чтобы получить случайный набор объектов из массива, используется функция random.choice:

choice(a, size=None, replace=True)
- где
* a — массив или число для генерации arange(a);
* size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
* replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

In [24]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['John' 'Nikita']


In [25]:
# На выходе получили массив из двух имён без повторений. 
# Если попытаться получить без повторений массив большего размера, чем имеется объектов в исходном, возникнет ошибка:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [26]:
# По умолчанию повторения включены, при большем размере чем массив, ошибки не возникает
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[2 4 3 4 4 1 3 2 3 5]


#### SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

In [27]:
# Зададим seed и посмотрим, что получится:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [28]:
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]


In [37]:
# Не забудьте импортировать numpy и сразу задать seed 2021
np.random.seed(2021)

# В simple сохранте случайное число в диапазоне от 0 до 1
simple = np.random.rand()

# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)

# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3,2))

# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2, 17, 2)

# Перемешайте числа в even так, чтобы массив even изменился
np.random.shuffle(even)

# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, size=3, replace=False)

# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
print (even)

[ 6 10  2  8 14 16  4 12]


In [30]:
num="-65536"
numint = np.int16(num)
print(numint)

0


In [31]:
def get_chess(a):
    mass=np.zeros([a,a])
    mass[::2, 1::2] = 1
    mass[1::2, ::2] = 1
    return mass

In [32]:
get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [33]:
from numpy import uint32


def shuffle_seed(array):
    # Напишите тело функции принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений),
    # а также seed, с которым этот массив был получен.
    seed_x = np.random.randint(0, 4294967296, dtype=uint32)
    np.random.seed(seed_x)
    return np.random.permutation(array), seed_x


In [34]:
array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([1, 3, 5, 4, 2]), 3670196057)

In [1]:
def min_max_dist(*vectors):
    # Задаем начальные значения
    min_ = -1
    max_ = -1
    i = 0
    while True:
        if len(vectors)-1 == i:
            # Если остался последний вектор, его сравнивать не с чем, выходим
            if min_ == -1:
                min_ = 0
            if max_ == -1:
                max_ = 0
            # Если это был единственный вектор - ставим мин и макс в 0
            break
        vector0 = vectors[i] # Сектор от которого считаем растояние до других векторов
        for ind in range(i+1, len(vectors)):
            ab = np.linalg.norm(vectors[ind]-vector0)
            if (min_ == -1) or (min_ > ab):
                min_ = ab
            if (max_ == -1) or (max_ < ab):
                max_ = ab
        i += 1
    return (min_, max_)

In [9]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2)

(5.196152422706632, 5.196152422706632)

In [10]:
def any_normal(*vectors):
    # Задаем начальные значения
    i = 0
    while True:
        if len(vectors)-1 == i:
            break
        vector0 = vectors[i] # Вектор от которого считаем скалярное произведение
        for ind in range(i+1, len(vectors)):
            ab = np.dot(vectors[ind],vector0)
            if ab == 0:
                return True
        i += 1
    return False

In [11]:
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


In [54]:
x_ar = np.array(
    [
    [-3, -3, -2],
    [-1, 0, 1],
    [2, 3, 4]
    ]
    )

In [52]:
a = np.array([-3, -3, -2])
b = np.array([-1, 0, 1])
c = np.array([2, 3, 4])

In [53]:
print(np.linalg.norm(a-b))
print(np.linalg.norm(a-c))
print(np.linalg.norm(c-b))

4.69041575982343
9.848857801796104
5.196152422706632


In [74]:
print(np.linalg.norm(x_ar[0, ::] - x_ar[2, ::]))

9.848857801796104


In [75]:
def get_loto(num):
    return np.random.randint(1,101,(num,5,5))
    # Напишите тело функции
    


In [76]:
get_loto(3)

array([[[ 90,  20,  30,  91,  98],
        [ 43,  68,  24,  98,  60],
        [ 92,  86,  24,  57,  19],
        [ 44, 100,  68,  91,  11],
        [100,  28,  25,  18,  62]],

       [[ 63,   8,  19,  76,  33],
        [ 99,  40,  48,  50,  11],
        [  1,  63,  18,  39,  36],
        [ 78,  28,  51,  83,  45],
        [ 20,   4,  74,  34,  81]],

       [[ 18,  25,   4,  33,  82],
        [ 58,  14,  82,  44,  69],
        [ 86,  56,  51,  54,  76],
        [ 79,  67,  71,  94,   4],
        [ 21,   5,  35,  66,  40]]])

In [91]:
import enum


def get_unique_loto(num):
    temp_arr = np.arange(1, 101)
    ret_arr = np.zeros((num, 5, 5))
    for ind, arrx in enumerate(ret_arr):
        ret_arr[ind] = np.random.choice(temp_arr, size=(5,5), replace=False)    
    return ret_arr


In [92]:
get_unique_loto(3)

array([[[ 77.,  59.,  86.,  23.,  60.],
        [ 33., 100.,  29.,  16.,  47.],
        [  7.,  64.,  78.,  10.,  63.],
        [ 62.,  50.,  79.,  39.,  52.],
        [ 89.,  97.,  22.,   3.,  73.]],

       [[ 44.,  58.,  91.,  81.,  76.],
        [ 35.,  46.,  66.,  89.,  85.],
        [ 71.,  56.,  12.,  93.,  77.],
        [ 33.,  49.,  74.,  60.,  95.],
        [ 70.,  69.,  79.,  37.,  86.]],

       [[ 48.,  71.,  31.,  95.,   2.],
        [ 77.,   5.,  23.,  54.,  78.],
        [ 91.,  92.,  81.,   1.,  85.],
        [ 43.,  39.,  26.,  62.,  51.],
        [  6.,  52.,  37.,  89.,  10.]]])