In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int32


In [5]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [6]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [7]:
arr[2] = 2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [8]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [9]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [10]:
arr[2] = 'test'

ValueError: invalid literal for int() with base 10: 'test'

In [12]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [13]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100])

In [14]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [15]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [17]:
print(arr.ndim)

print(nd_arr.ndim)

1
2


In [18]:
print(arr.size)
print(nd_arr.size)
print(arr.shape)
print(nd_arr.shape)

5
9
(5,)
(3, 3)


In [19]:
print(arr.itemsize)
print(nd_arr.itemsize)

1
2


Действительно, в arr хранятся числа в виде int8 (8 бит => 1 байт), а в nd_arr — в виде int16 (16 бит => 2 байта).

In [20]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [21]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [24]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [25]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [26]:
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [27]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [28]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1111111111111111
0.1


In [30]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45
