In [1]:
import numpy as np
# Для начала произведём сложение двух векторов:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [2]:
# Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
# Чтобы сложить два этих списка поэлементно, нам пришлось бы написать списочное сокращение с применением функции zip():
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

`Для совершения арифметических операций с векторами они должны быть одинаковой длины.`

In [4]:
# Поэлементно умножим два вектора одинаковой длины:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [5]:
# А теперь создадим vec2, который будет на один элемент короче, чем vec1:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
 
vec1 * vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [6]:
# Исключением является случай, когда операция происходит с вектором и одним числом.
# Например, вектор целиком можно умножить на число или возвести в степень этого числа:
vec = np.arange(5)
print(vec * 10)
print(vec ** 2)

[ 0 10 20 30 40]
[ 0  1  4  9 16]


In [7]:
# Также векторы можно сравнивать друг с другом поэлементно:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

In [8]:
# Аналогично можно сравнивать вектор с числом:

vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [12]:
# Посчитаем длину следующего вектора:
vec = np.array([3, 4])


In [13]:
# Для начала воспользуемся формулой: возведём все элементы в квадрат, посчитаем их сумму, а затем найдём квадратный корень.
length = np.sqrt(np.sum(vec ** 2))
print(length)

5.0


In [14]:
# Но можно было поступить проще. В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.
# Для вычисления длины вектора нам потребуется функция norm:
length = np.linalg.norm(vec)
print(length)

5.0


#### Растояние между двумя веторами
`По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.`

In [15]:
# Реализуем вычисление расстояния в коде. Сначала — «сложным» способом напрямую из формулы:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

12.206555615733702

In [16]:
# А теперь применим более простой способ — используем уже известную нам функцию np.linalg.norm:
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

### Скалярное произведение

In [17]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

In [18]:
# используем функцию np.dot(x, y):
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [20]:
# Если скалярное произведение = 0, то векторы перпендикулярны
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

`На практике векторы используются, например, для оценки текстов. С помощью специальных преобразований слова в тексте превращаются в числовые векторы. Затем через определение направлений полученных векторов можно находить слова-синонимы и антонимы, а также оценивать общую эмоциональную окраску текста. Такие алгоритмы для анализа данных используются, чтобы автоматически по отзывам определять степень удовлетворённости клиентов продуктом.`

In [24]:
# Задание 49.7.4
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

# Пишите здесь команды, который помогут
# найти ответы на вопросы
a_length = np.linalg.norm(a)
b_length = np.linalg.norm(b)
c_length = np.linalg.norm(c)
ab = np.linalg.norm(a+b)
bc = np.linalg.norm(b+c)
ac = np.linalg.norm(a+c)
print('a и b - ', a_length+b_length==ab)
print('b и c - ', c_length+b_length==bc)
print('a и c - ', a_length+c_length==ac)
# 49.7.5 (Растояние между векторами > 100)
ab_distance = np.linalg.norm(a - b)
ac_distance = np.linalg.norm(a - c)
bc_distance = np.linalg.norm(b - c)
print('Растояние a-b {}'.format(ab_distance))
print('Растояние a-c {}'.format(ac_distance))
print('Растояние b-c {}'.format(bc_distance))
# 49.7.6 (Скалярное произведение)
ab_scalar = np.dot(a,b)
ac_scalar = np.dot(a,c)
bc_scalar = np.dot(c,b)
print('a - b перпендикулярны: ', ab_scalar==0)
print('a - c перпендикулярны: ', ac_scalar==0)
print('b - c перпендикулярны: ', bc_scalar==0)

a и b -  False
b и c -  False
a и c -  True
Растояние a-b 85.901105930017
Растояние a-c 49.13247398615299
Растояние b-c 120.6358155772986
a - b перпендикулярны:  False
a - c перпендикулярны:  False
b - c перпендикулярны:  False


In [25]:
# Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе.
# Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():
vec = np.array([2,7,18,28,18,1,8,4])

print(vec.min())

print(np.max(vec))

1
28


In [ ]:
# Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!
vec.mean()