In [1]:
import numpy as np
np.random.rand()

0.6071858026815177

In [2]:
np.random.rand() * 100

74.50324340243205

In [3]:
np.random.rand(5)

array([0.90284563, 0.9022289 , 0.02831755, 0.34722597, 0.87133027])

In [4]:
np.random.rand(2, 3)

array([[0.78768788, 0.45011729, 0.31241044],
       [0.83389529, 0.83314255, 0.32581746]])

In [5]:
# Функция rand может принимать неограниченное число целых чисел для задания формы массива:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[7.91628273e-01, 8.84933356e-01, 4.13248014e-01, ...,
            6.52613180e-01, 6.28039940e-01, 2.58486015e-01],
           [1.78028074e-01, 9.09218415e-01, 2.96160343e-01, ...,
            7.57577329e-01, 3.34651267e-01, 2.57446554e-01],
           [3.99183504e-02, 7.93081320e-01, 5.83359445e-01, ...,
            1.42989523e-01, 1.79009715e-01, 3.82154750e-01],
           ...,
           [9.80453850e-01, 4.76060184e-03, 1.81007464e-01, ...,
            3.38274084e-01, 5.58439605e-01, 8.18690610e-01],
           [6.40908913e-02, 9.21430995e-01, 6.64012611e-01, ...,
            2.06927108e-01, 1.67792559e-01, 4.05605177e-01],
           [2.88279552e-01, 6.35513982e-01, 6.64303630e-01, ...,
            2.72982385e-01, 4.56086832e-01, 9.61149197e-01]],

          [[3.46828834e-01, 3.02301233e-02, 9.08671042e-01, ...,
            2.13066035e-01, 2.52421327e-01, 3.94557041e-01],
           [2.87488386e-01, 2.31883298e-01, 2.96026803e-01, ...,
            1.55126459e-01, 2.59429

In [6]:
# Если передать в rand кортеж, возникнет ошибка
shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [7]:
# Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:
shape = (3, 4)
np.random.rand(*shape)

array([[0.43320556, 0.48349057, 0.61667316, 0.34533358],
       [0.71332441, 0.49028155, 0.85506998, 0.9174821 ],
       [0.40355249, 0.99481252, 0.18640429, 0.76365893]])

In [8]:
# Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1,
# которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:
shape = (2, 3)
np.random.sample(shape)

array([[0.05754376, 0.82974455, 0.95754737],
       [0.51110668, 0.11046254, 0.19835629]])

In [9]:
# Не всегда требуются числа в диапазоне именно от 0 до 1.
# На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон,
# однако это не требуется делать самостоятельно — в NumPy доступна функция uniform:

# uniform(low=0.0, high=1.0, size=None)

# Первые два аргумента — нижняя и верхняя границы диапазона в формате float, 
# третий опциональный аргумент — форма массива (если не задан, возвращается одно число). 
# Форма массива задаётся кортежем или одним числом.

np.random.uniform()


0.2709752991617045

In [13]:
np.random.uniform(-30, 50)

23.871855047352383

In [14]:
np.random.uniform(0.5, 0.75, size=5)

array([0.70876515, 0.74000032, 0.69505098, 0.56500106, 0.72010243])

In [15]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-344.76381511, -773.75781575, -452.10550826],
       [-491.42927376, -142.84871242,  350.51528713]])

### ГЕНЕРАЦИЯ INT

- randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

* Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
* Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
* size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
* dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.


In [16]:
# Сгенерируем таблицу 2x3 от 0 до 3 включительно:
np.random.randint(4, size=(2,3))

array([[1, 1, 1],
       [2, 1, 0]])

In [17]:
np.random.randint(6, 12, size=(3,3))

array([[11, 11,  9],
       [ 8,  7, 11],
       [ 9,  8, 10]])

#### ГЕНЕРАЦИЯ ВЫБОРОК

In [18]:
# Возьмём массив из целых чисел от 0 до 5 и перемешаем его:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))
arr

[0 1 2 3 4 5]
None


array([4, 2, 5, 3, 0, 1])

In [26]:
# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation.
# Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['Pink Floyd' 'The Beatles' 'Deep Purple' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [20]:
# Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n),
# где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.
np.random.permutation(10)

array([7, 2, 8, 1, 0, 3, 9, 4, 5, 6])

Чтобы получить случайный набор объектов из массива, используется функция random.choice:

choice(a, size=None, replace=True)
- где
* a — массив или число для генерации arange(a);
* size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
* replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

In [21]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Maria' 'John']


In [22]:
# На выходе получили массив из двух имён без повторений. 
# Если попытаться получить без повторений массив большего размера, чем имеется объектов в исходном, возникнет ошибка:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [23]:
# По умолчанию повторения включены, при большем размере чем массив, ошибки не возникает
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[6 4 3 6 2 3 3 5 5 5]


#### SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

In [24]:
# Зададим seed и посмотрим, что получится:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [25]:
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]


In [27]:
# Не забудьте импортировать numpy и сразу задать seed 2021
np.random.seed(2021)

# В simple сохранте случайное число в диапазоне от 0 до 1
simple = np.random.rand()

# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)

# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3,2))

# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = [2,4,6,8,10,12,14,16]

# Перемешайте числа в even так, чтобы массив even изменился
np.random.shuffle(even)

# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, size=3, replace=False)

# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)

In [29]:
num="-65536"
numint = np.int16(num)
print(numint)

0


In [47]:
def get_chess(a):
    mass=np.zeros([a,a])
    mass[::2, 1::2] = 1
    mass[1::2, ::2] = 1
    return mass

In [52]:
get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [59]:
from numpy import uint32


def shuffle_seed(array):
    # Напишите тело функции принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений),
    # а также seed, с которым этот массив был получен.
    seed_x = np.random.randint(0, 4294967296, dtype=uint32)
    np.random.seed(seed_x)
    return np.random.permutation(array), seed_x


In [62]:
array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([1, 2, 5, 3, 4]), 3105880932)